# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160127_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='testfield',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 27, 22, 49, 52, 350000)),
        ),
    ]
